In [10]:
import pandas as pd
import os

In [11]:
pwd = os.getcwd()

In [12]:
filepath = pwd + "/simple_csv.csv"

In [13]:
first_import = pd.read_csv(filepath,nrows=10)
first_import

,movie_title,content_rating,genres,directors,authors,actors,original_release_date,streaming_release_date,runtime,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,Percy Jackson & the Olympians: The Lightning T...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",12/02/2010,25/11/2015,119,20th Century Fox,Rotten,49,149,Spilled,53,254421,43,73,76
1,Please Give,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",30/04/2010,04/09/2012,90,Sony Pictures Classics,Certified-Fresh,87,142,Upright,64,11574,44,123,19
2,10,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",05/10/1979,24/07/2014,122,Waner Bros.,Fresh,67,24,Spilled,53,14684,2,16,8
3,12 Angry Men (Twelve Angry Men),NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",13/04/1957,13/01/2017,95,Criterion Collection,Certified-Fresh,100,54,Upright,97,105386,6,54,0
4,"20,000 Leagues Under The Sea",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",01/01/1954,10/06/2016,127,Disney,Fresh,89,27,Upright,74,68918,5,24,3
5,"10,000 B.C.",PG-13,"Action & Adventure, Classics, Drama",Roland Emmerich,"Harald Kloser, Roland Emmerich","Steven Strait, Camilla Belle, Cliff Curtis, Jo...",07/03/2008,22/06/2013,109,Warner Bros. Pictures,Rotten,8,149,Spilled,37,411140,37,12,137
6,The 39 Steps,NR,"Action & Adventure, Classics, Mystery & Suspense",Alfred Hitchcock,"Alma Reville, Charles Bennett, Ian Hay, Alfred...","Robert Donat, Madeleine Carroll, Godfrey Tearl...",01/08/1935,12/01/2017,80,Gaumont British Distributors,Certified-Fresh,96,51,Upright,86,23890,8,49,2
7,3:10 to Yuma,NR,"Classics, Drama, Western",Delmer Daves,Halsted Welles,"Glenn Ford, Van Heflin, Felicia Farr, Leora Da...",07/08/1957,16/04/2012,92,Columbia Pictures,Fresh,96,28,Upright,79,9243,6,27,1
8,Charly (A Heartbeat Away),PG,"Comedy, Drama, Romance",Adam Thomas Anderegg,"Jack Weyland, Janine Whetton Gilbert","Heather Beers, Gary Neilson, Lisa McCammon, Ja...",27/09/2002,22/05/2017,103,Excel Entertainment,Rotten,20,10,Upright,87,4819,0,2,8
9,Abraham Lincoln,NR,"Classics, Drama",D.W. Griffith,"Gerrit J. Lloyd, Stephen Vincent Ben√©t","Walter Huston, Una Merkel, Kay Hammond, Ian Ke...",08/11/1930,03/12/2013,97,United Artists,Fresh,82,11,Spilled,40,457,4,9,2

In [14]:
first_import["actors"]

0    Logan Lerman, Brandon T. Jackson, Alexandra Da...
1    Catherine Keener, Amanda Peet, Oliver Platt, R...
2    Dudley Moore, Bo Derek, Julie Andrews, Robert ...
3    Martin Balsam, John Fiedler, Lee J. Cobb, E.G....
4    James Mason, Kirk Douglas, Paul Lukas, Peter L...
5    Steven Strait, Camilla Belle, Cliff Curtis, Jo...
6    Robert Donat, Madeleine Carroll, Godfrey Tearl...
7    Glenn Ford, Van Heflin, Felicia Farr, Leora Da...
8    Heather Beers, Gary Neilson, Lisa McCammon, Ja...
9    Walter Huston, Una Merkel, Kay Hammond, Ian Ke...
Name: actors, dtype: object

In [35]:
first_import["new_column"]=1
first_import["new_column2"]=list(range(10))
first_import["added output"]=first_import["new_column"]+first_import["new_column2"]
first_import

ValueError: Length of values (10) does not match length of index (17712)

In [16]:
first_import.iloc[1000:1050, [0,9]]

Empty DataFrame
Columns: [movie_title, production_company]
Index: []

In [17]:
first_import = pd.read_csv(filepath)
first_import.iloc[17000]

movie_title                                                             Walk on Water
content_rating                                                                      R
genres                              Art House & International, Drama, Mystery & Su...
directors                                                                   Eytan Fox
authors                                                                  Gal Uchovsky
actors                              Lior Ashkenazi, Knut Berger, Carolina Peters, ...
original_release_date                                                      04/03/2005
streaming_release_date                                                     09/12/2016
runtime                                                                         102.0
production_company                                               Roadside Attractions
tomatometer_status                                                              Fresh
tomatometer_rating                                                               72.0
tomatometer_count                                                                76.0
audience_status                                                               Upright
audience_rating                                                                  87.0
audience_count                                                                 5724.0
tomatometer_top_critics_count                                                      25
tomatometer_fresh_critics_count                                                    55
tomatometer_rotten_critics_count                                                   21
Name: 17000, dtype: object

In [18]:
list(first_import.columns)

['movie_title',
 'content_rating',
 'genres',
 'directors',
 'authors',
 'actors',
 'original_release_date',
 'streaming_release_date',
 'runtime',
 'production_company',
 'tomatometer_status',
 'tomatometer_rating',
 'tomatometer_count',
 'audience_status',
 'audience_rating',
 'audience_count',
 'tomatometer_top_critics_count',
 'tomatometer_fresh_critics_count',
 'tomatometer_rotten_critics_count']

In [19]:
first_import.describe()

,runtime,tomatometer_rating,tomatometer_count,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
count,17398.000000,17668.000000,17668.000000,17416.000000,1.741500e+04,17712.000000,17712.000000,17712.000000
mean,102.214048,60.884763,57.139801,60.554260,1.439401e+05,14.586326,36.374831,20.703139
std,18.702511,28.443348,68.370047,20.543369,1.763577e+06,15.146349,52.601038,30.248435
min,5.000000,0.000000,5.000000,0.000000,5.000000e+00,0.000000,0.000000,0.000000
25%,90.000000,38.000000,12.000000,45.000000,7.075000e+02,3.000000,6.000000,3.000000
50%,99.000000,67.000000,28.000000,63.000000,4.277000e+03,8.000000,16.000000,8.000000
75%,111.000000,86.000000,75.000000,78.000000,2.498800e+04,23.000000,44.000000,24.000000
max,266.000000,100.000000,574.000000,100.000000,3.579764e+07,69.000000,497.000000,303.000000

In [20]:
first_import.corr()

,runtime,tomatometer_rating,tomatometer_count,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
runtime,1.000000,0.089672,0.272304,0.229088,0.062672,0.243070,0.267346,0.149550
tomatometer_rating,0.089672,1.000000,0.083565,0.654068,0.013408,0.055090,0.339090,-0.400668
tomatometer_count,0.272304,0.083565,1.000000,0.147596,0.127442,0.925711,0.907241,0.681868
audience_rating,0.229088,0.654068,0.147596,1.000000,0.021885,0.130499,0.310079,-0.205912
audience_count,0.062672,0.013408,0.127442,0.021885,1.000000,0.124026,0.119320,0.079990
tomatometer_top_critics_count,0.243070,0.055090,0.925711,0.130499,0.124026,1.000000,0.807543,0.687473
tomatometer_fresh_critics_count,0.267346,0.339090,0.907241,0.310079,0.119320,0.807543,1.000000,0.311143
tomatometer_rotten_critics_count,0.149550,-0.400668,0.681868,-0.205912,0.079990,0.687473,0.311143,1.000000

In [21]:
first_import["genres"].unique()

array(['Action & Adventure, Comedy, Drama, Science Fiction & Fantasy',
       'Comedy', 'Comedy, Romance', ...,
       'Animation, Art House & International, Drama, Science Fiction & Fantasy, Romance',
       'Art House & International, Romance',
       'Action & Adventure, Drama, Horror, Kids & Family, Mystery & Suspense'],
      dtype=object)

In [22]:
first_import[first_import["genres"]=="Drama"]

,movie_title,content_rating,genres,directors,authors,actors,original_release_date,streaming_release_date,runtime,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
12,The Lost City,R,Drama,Andy Garcia,"G. Cabrera Infante, Guillermo Cabrera Infante","Andy Garcia, Dustin Hoffman, Bill Murray, In√©s...",03/09/2005,23/03/2017,143.0,Magnolia Pictures,Rotten,25.0,83.0,Upright,64.0,25944.0,37,21,62
13,The Breaking Point,NR,Drama,Michael Curtiz,Ranald MacDougall,"John Garfield, Patricia Neal, Phyllis Thaxter,...",06/10/1950,25/08/2016,97.0,Warner Home Video,Fresh,100.0,10.0,Upright,86.0,335.0,1,10,0
55,Dirty,R,Drama,Chris Fisher,"Chris Fisher, Gil Reavill, Eric Saks","Cuba Gooding Jr., Wyclef Jean, Keith David, Cl...",24/02/2006,16/04/2012,97.0,SNP Inc.,Rotten,21.0,28.0,Spilled,42.0,7326.0,10,6,22
58,All Quiet on the Western Front,NR,Drama,Delbert Mann,Paul Monash,"Richard Thomas, Ernest Borgnine, Ian Holm, Don...",NaN,16/04/2018,156.0,Unknown,Fresh,100.0,5.0,Upright,69.0,7588.0,0,5,0
90,Alexandra,NR,Drama,Aleksandr Sokurov,Aleksandr Sokurov,"Galina Vishnevskaya, Vasily Shetvtsov, Vasily ...",25/05/2007,11/02/2015,95.0,The Cinema Guild,Certified-Fresh,88.0,59.0,Upright,69.0,1333.0,24,52,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17655,Your Son (Tu Hijo),NR,Drama,Miguel √Ångel Vivas,Alberto Marini,"Jos√© Coronado, Ana Wagener, Asia Ortega, Pol M...",NaN,01/03/2019,103.0,Netflix,Fresh,100.0,5.0,Upright,60.0,35.0,0,5,0
17657,You're Not You,R,Drama,George C. Wolfe,"Jordan Roberts, Shana Feste","Hilary Swank, Emmy Rossum, Josh Duhamel, Marci...",10/10/2014,21/06/2019,102.0,Entertainment One Films,Rotten,48.0,23.0,Upright,70.0,1636.0,10,11,12
17674,Zandalee,R,Drama,Sam Pillsbury,Mari Kornhauser,"Nicolas Cage, Judge Reinhold, Erika Anderson, ...",09/05/1991,18/09/2015,94.0,Live Home Video,Rotten,33.0,6.0,Spilled,29.0,1178.0,1,2,4
17684,Zero Dark Thirty,R,Drama,Kathryn Bigelow,Mark Boal,"Jessica Chastain, Jason Clarke, Joel Edgerton,...",11/01/2013,07/09/2014,157.0,Columbia Pictures,Certified-Fresh,91.0,298.0,Upright,80.0,197142.0,58,272,26
17687,Zero Motivation,NR,Drama,Talya Lavie,Talya Lavie,"Dana Ivgy, Nelly Tagar, Shani Klein, Heli Twit...",03/12/2014,20/03/2017,100.0,Zeitgeist Films,Certified-Fresh,88.0,49.0,Upright,77.0,1460.0,16,44,6

In [23]:
first_import[(first_import["genres"]=="Comedy")|(first_import["actors"]=="Reilly Dolman")]

,movie_title,content_rating,genres,directors,authors,actors,original_release_date,streaming_release_date,runtime,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
1,Please Give,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",30/04/2010,04/09/2012,90.0,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19
23,Bandwagon,R,Comedy,John Schultz,John Schultz,"Matthew Hennessey, Kevin Corrigan, Steve Parla...",12/09/1997,NaN,103.0,Avalanche Entertainment,Fresh,80.0,5.0,Upright,91.0,386.0,1,4,1
27,A Tale of Two Pizzas,PG,Comedy,Vincent Sassone,Vincent Sassone,"Vincent Pastore, Vincent Sassone, Frank Vincen...",07/11/2003,16/01/2018,82.0,NaN,Rotten,38.0,8.0,NaN,NaN,NaN,5,3,5
29,Going the Distance,R,Comedy,Mark Griffiths,"Eric Goodman, Kelly Senecal","Christopher Jacot, Shawn Roberts, Ryan Bellevi...",20/08/2004,10/03/2017,93.0,S√©ville Pictures,Rotten,0.0,5.0,Upright,61.0,13033.0,2,0,5
53,When Do We Eat?,R,Comedy,Salvador Litvak,"Salvador Litvak, Nina Davidovich","Michael Lerner, Lesley Ann Warren, Jack Klugma...",07/04/2006,22/05/2017,87.0,ThinkFilm,Rotten,42.0,38.0,Upright,68.0,1121.0,19,16,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17624,"You, Me and Dupree",PG-13,Comedy,"Anthony Russo, Joe Russo",Michael LeSieur,"Owen Wilson, Kate Hudson, Matt Dillon, Michael...",13/07/2006,12/02/2014,109.0,Universal Pictures,Rotten,20.0,169.0,Spilled,50.0,448203.0,42,34,135
17636,Young Einstein,PG,Comedy,Yahoo Serious,"David Roach, Yahoo Serious","Yahoo Serious, Odile Le Clezio, John Howard (I...",01/01/1988,01/01/2008,89.0,Warner Home Video,Rotten,36.0,33.0,Spilled,50.0,12132.0,10,12,21
17651,Your Highness,R,Comedy,David Gordon Green,"Ben Best, Danny McBride (IV)","Danny McBride (IV), James Franco, Rasmus Hardi...",08/04/2011,23/05/2016,102.0,Universal Pictures,Rotten,28.0,181.0,Spilled,34.0,54289.0,44,50,131
17683,Zero Charisma,NR,Comedy,"Katie Graham, Andrew Matthews",Andrew Matthews,"Sam Eidson, Anne Gee Byrd, Garrett Graham, Bro...",11/10/2013,10/08/2016,88.0,Tribeca Film,Fresh,76.0,25.0,Spilled,55.0,1109.0,8,19,6
17705,Zoolander 2,PG-13,Comedy,Ben Stiller,"Nicholas Stoller, John Hamburg, Ben Stiller, J...","Ben Stiller, Owen Wilson, Will Ferrell, Penelo...",12/02/2016,30/12/2016,102.0,Paramount Pictures,Rotten,22.0,232.0,Spilled,20.0,41745.0,48,51,181

In [24]:
first_import["computer_data"]=pd.to_datetime(first_import["original_release_date"])
first_import

,movie_title,content_rating,genres,directors,authors,actors,original_release_date,streaming_release_date,runtime,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count,computer_data
0,Percy Jackson & the Olympians: The Lightning T...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",12/02/2010,25/11/2015,119.0,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76,2010-12-02
1,Please Give,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",30/04/2010,04/09/2012,90.0,Sony Pictures Classics,Certified-Fresh,87.0,142.0,Upright,64.0,11574.0,44,123,19,2010-04-30
2,10,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",05/10/1979,24/07/2014,122.0,Waner Bros.,Fresh,67.0,24.0,Spilled,53.0,14684.0,2,16,8,1979-05-10
3,12 Angry Men (Twelve Angry Men),NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",13/04/1957,13/01/2017,95.0,Criterion Collection,Certified-Fresh,100.0,54.0,Upright,97.0,105386.0,6,54,0,1957-04-13
4,"20,000 Leagues Under The Sea",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",01/01/1954,10/06/2016,127.0,Disney,Fresh,89.0,27.0,Upright,74.0,68918.0,5,24,3,1954-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17707,Zoot Suit,R,"Drama, Musical & Performing Arts",Luis Valdez,Luis Valdez,"Daniel Valdez, Edward James Olmos, Charles Aid...",02/10/1981,19/04/2016,104.0,MCA Universal Home Video,Rotten,56.0,9.0,Upright,74.0,1195.0,2,5,4,1981-02-10
17708,Zootopia,PG,"Action & Adventure, Animation, Comedy","Byron Howard, Rich Moore, Jared Bush","Jared Bush, Phil Johnston","J.K. Simmons, Kristen Bell, Octavia Spencer, A...",04/03/2016,07/06/2016,108.0,Walt Disney Animation Studios,Certified-Fresh,98.0,291.0,Upright,92.0,101511.0,50,285,7,2016-04-03
17709,Zorba the Greek,NR,"Action & Adventure, Art House & International,...",NaN,NaN,"Anthony Quinn, Alan Bates, Irene Papas, Lila K...",17/12/1964,25/11/2015,142.0,Fox,Fresh,80.0,10.0,Upright,86.0,7146.0,0,8,2,1964-12-17
17710,Zulu,PG,"Classics, Drama","Cy Endfield, Cyril Endfield","Cy Endfield, John Prebble","Stanley Baker, Jack Hawkins, Ulla Jacobsson, J...",17/06/1964,08/01/2017,135.0,Paramount Pictures,Fresh,96.0,23.0,Upright,91.0,30193.0,6,22,1,1964-06-17
17711,Zulu Dawn,PG,"Action & Adventure, Art House & International,...",Douglas Hickox,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",14/12/1979,22/03/2016,121.0,Tango Entertainment,Rotten,50.0,8.0,Upright,62.0,4469.0,0,4,4,1979-12-14

In [25]:
first_import["computer_data"]

0       2010-12-02
1       2010-04-30
2       1979-05-10
3       1957-04-13
4       1954-01-01
           ...
17707   1981-02-10
17708   2016-04-03
17709   1964-12-17
17710   1964-06-17
17711   1979-12-14
Name: computer_data, Length: 17712, dtype: datetime64[ns]

In [26]:
first_import["computer_data"].dropna()

0       2010-12-02
1       2010-04-30
2       1979-05-10
3       1957-04-13
4       1954-01-01
           ...
17707   1981-02-10
17708   2016-04-03
17709   1964-12-17
17710   1964-06-17
17711   1979-12-14
Name: computer_data, Length: 16546, dtype: datetime64[ns]

In [27]:
from datetime import datetime as dt

In [28]:
first_import["computer_data"].fillna(dt(2010, 12,2),inplace=True)

In [29]:
first_import["unix_time"]=first_import["computer_data"].astype(str)
first_import

,movie_title,content_rating,genres,directors,authors,actors,original_release_date,streaming_release_date,runtime,production_company,...,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count,computer_data,unix_time
0,Percy Jackson & the Olympians: The Lightning T...,PG,"Action & Adventure, Comedy, Drama, Science Fic...",Chris Columbus,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",12/02/2010,25/11/2015,119.0,20th Century Fox,...,49.0,149.0,Spilled,53.0,254421.0,43,73,76,2010-12-02,2010-12-02
1,Please Give,R,Comedy,Nicole Holofcener,Nicole Holofcener,"Catherine Keener, Amanda Peet, Oliver Platt, R...",30/04/2010,04/09/2012,90.0,Sony Pictures Classics,...,87.0,142.0,Upright,64.0,11574.0,44,123,19,2010-04-30,2010-04-30
2,10,R,"Comedy, Romance",Blake Edwards,Blake Edwards,"Dudley Moore, Bo Derek, Julie Andrews, Robert ...",05/10/1979,24/07/2014,122.0,Waner Bros.,...,67.0,24.0,Spilled,53.0,14684.0,2,16,8,1979-05-10,1979-05-10
3,12 Angry Men (Twelve Angry Men),NR,"Classics, Drama",Sidney Lumet,Reginald Rose,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",13/04/1957,13/01/2017,95.0,Criterion Collection,...,100.0,54.0,Upright,97.0,105386.0,6,54,0,1957-04-13,1957-04-13
4,"20,000 Leagues Under The Sea",G,"Action & Adventure, Drama, Kids & Family",Richard Fleischer,Earl Felton,"James Mason, Kirk Douglas, Paul Lukas, Peter L...",01/01/1954,10/06/2016,127.0,Disney,...,89.0,27.0,Upright,74.0,68918.0,5,24,3,1954-01-01,1954-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17707,Zoot Suit,R,"Drama, Musical & Performing Arts",Luis Valdez,Luis Valdez,"Daniel Valdez, Edward James Olmos, Charles Aid...",02/10/1981,19/04/2016,104.0,MCA Universal Home Video,...,56.0,9.0,Upright,74.0,1195.0,2,5,4,1981-02-10,1981-02-10
17708,Zootopia,PG,"Action & Adventure, Animation, Comedy","Byron Howard, Rich Moore, Jared Bush","Jared Bush, Phil Johnston","J.K. Simmons, Kristen Bell, Octavia Spencer, A...",04/03/2016,07/06/2016,108.0,Walt Disney Animation Studios,...,98.0,291.0,Upright,92.0,101511.0,50,285,7,2016-04-03,2016-04-03
17709,Zorba the Greek,NR,"Action & Adventure, Art House & International,...",NaN,NaN,"Anthony Quinn, Alan Bates, Irene Papas, Lila K...",17/12/1964,25/11/2015,142.0,Fox,...,80.0,10.0,Upright,86.0,7146.0,0,8,2,1964-12-17,1964-12-17
17710,Zulu,PG,"Classics, Drama","Cy Endfield, Cyril Endfield","Cy Endfield, John Prebble","Stanley Baker, Jack Hawkins, Ulla Jacobsson, J...",17/06/1964,08/01/2017,135.0,Paramount Pictures,...,96.0,23.0,Upright,91.0,30193.0,6,22,1,1964-06-17,1964-06-17
17711,Zulu Dawn,PG,"Action & Adventure, Art House & International,...",Douglas Hickox,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",14/12/1979,22/03/2016,121.0,Tango Entertainment,...,50.0,8.0,Upright,62.0,4469.0,0,4,4,1979-12-14,1979-12-14

In [30]:
first_import.groupby("tomatometer_status")["movie_title"].count().reset_index().sort_values(by="movie_title", ascending=False)

  tomatometer_status  movie_title
2             Rotten         7565
1              Fresh         6844
0    Certified-Fresh         3259